# app
application:
  name: tsp-web
server:
  port: 9202
  servlet:
    path: /tsp-web
tsp-server:
  url: http://192.168.41.57:9200/tsp-server

tsp-server2:
  url: http://192.168.41.57:9208/tsp-server

tsp-collect:
  url: http://192.168.41.57:9205/tsp-collect

tsp-market:
  url: http://192.168.41.57:9206/tsp-market


# log
logging:
  level.com.iquantex.tspweb.dao: debug
  file: log/tsp-web.log
management.endpoints.web.exposure.include: '*'

# spring
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.116.18.157:1521/sigma_dev
    username: cs
    password: QuanTex_CS
  output:
    ansi:
      enabled: detect
  kafka:
    bootstrap-servers: 10.116.18.46:9092
    template:
      default-topic: calendar-calendarEvent
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-commit-interval: 100
      auto-offset-reset: earliest
  redis:
    database: 3
    host: 192.168.41.41
    port: 6379
    time: 10000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

websocket:
  topic: web_socket
  group: tsp-web-dev

# mybatis
mybatis:
  mapper-locations: classpath:com/iquantex/tspweb/dao/basexml/*.xml
  configuration:
    map-underscore-to-camel-case: true
    variables.tsp_c: TSP_C

pagehelper:
  helperDialect: oracle
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true

# phoenix
quantex:
  phoenix:
    mq:
      address: 10.116.18.46:9092
      type: kafka
    client:
      name: tsp-web
      mq-group: tsp-web
      subscribe-cmd: false
      cmd-topic: command_topic
      subscribe-event: false
      event-topic: event_topic
      need-rpc: true
      rpc-topic: rpc_topic
      payload-deserialize: true

#apollo
#enable load properties
apollo:
  bootstrap:
    enabled: true
    namespaces: application


#统一交换平台配置
unifiedexchange:
  clientId: TSP
  ZkServer: 192.168.42.101:2181,192.168.42.102:2181,192.168.42.104:2181
  Encoding: GBK
  timeOut: 30
  confDir: .
  #pro
  #ZkServer=10.10.8.70:2181,10.10.8.71:2181,10.10.8.72:2181
  #dev
  #ZkServer=192.168.42.88:2181
  #sit
  #ZkServer=192.168.42.95:2181
  #uat




#hscei 行情
hscei:
  amount: 0.0
  avgPrice: 0.0
  closePrice: 0.0
  highPrice: 0.0
  iopv: 0.0
  lastPrice: 0.0
  lowPrice: 0.0
  marketNo: 1545
  openPrice: 0.0
  preclosePrice: 0.0
  stockCode: HSCEI
  stockStatus: 0
  timestamp: 0
  volume: 0.0
  windMarketCode: CS
  csi:
    closePrice: 0.0
    closePrice2: 0.0
    closePrice3: 0.0
    currencySymbol: 0
    dealAmount: 1.217701315E9
    dealBalance: 1646731.2753
    exchangeRate: 1.0
    iOPV: 0.0
    lastPrice: 0.0
    maxPrice: 2401.2642
    minPrice: 2389.7321
    openPrice: 0.0
    recordNo: 1181
    relatedMarket: 3
    transDate: 20190425
    transTime: 102717
    upDown: -8.28
    upDownLimit: -0.0034